- name: installating python3 dependencies
  apt: pkg={{item}} state=present
  with_items:
  - python3-dev
  - python3-matplotlib
  - python3-cairo
  - python3-scipy
  - python3-numpy

- name: installating graph-tool for python3
  apt: pkg=python3-graph-tool force=yes state=present